#services:
#  postgres:
#    container_name: ms-postgres
#    image: postgres:15.1-alpine
#    restart: always
#    volumes:
#      - eventpg:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=raegan
#    networks:
#      - ms-net
#    ports:
#      - "5432:5432"
#
#
#networks:
#  ms-net:
#    driver: bridge
#
#volumes:
#  eventpg:
version: '3.8'

services:
  mysql:
    container_name: ms-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: venueservicedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge

volumes:
  mysql_data:
