server:
    port: 9090
spring:
    application:
        name: API-GATEWAY
    config:
        import:
            - configserver:http://localhost:9296
    cloud:
        gateway:
            routes:
                - id: EVENT-SERVICE
                  uri: lb://EVENT-SERVICE
                  predicates:
                      - Path=/api/events**, /api/categories**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: eventServiceCB
                        fallbackUri: forward:/eventServiceFallBack
                    - name: RequestRateLimiter
                      args:
                        redis-rate-limiter.replenishRate: 1
                        redis-rate-limiter.burstCapacity: 1
                        redis-rate-limiter.requestedTokens: 1

                - id: VENUE-SERVICE
                  uri: lb://VENUE-SERVICE
                  predicates:
                      - Path=/api/venues**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: venueServiceCB
                        fallbackUri: forward:/venueServiceFallBack
                    - name: RequestRateLimiter
                      args:
                        redis-rate-limiter.replenishRate: 1
                        redis-rate-limiter.burstCapacity: 1
                        redis-rate-limiter.requestedTokens: 1

        discovery:
            enabled: true
okta:
  oauth2:
    issuer: https://dev-64047080.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaghpny2qKXzdlKD5d7
    client-secret: m9XUFZG470xBWOrksRkeNt_AKaolsZ0wZ2FY-ugtX8JNVIwtihBq0JjkOj-1J8Cs
    scopes: openid,email,profile,offline_access