server:
    port: 8081
spring:
    application:
        name: EVENT-SERVICE
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/eventservicedb
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    config:
        import: configserver:http://localhost:9296

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://dev-64047080.okta.com/oauth2/default
            client:
                registration:
                    internal-client:
                        provider: okta
                        authorizationGrantType: client_credentials
                        scope:
                            - internal
                        clientId: 0oaghpny2qKXzdlKD5d7
                        clientSecret: m9XUFZG470xBWOrksRkeNt_AKaolsZ0wZ2FY-ugtX8JNVIwtihBq0JjkOj-1J8Cs

resilience4j:
    circuitbreaker:
        instances:
            external:
                event-consumer-buffer-size: 10
                failure-rate-threshold: 50
                minimum-number-of-calls: 5
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state: 5s
                permitted-number-of-calls-in-half-open-state: 3
                sliding-window-size: 10
                sliding-window-type: COUNT_BASED
#eureka:
#    instance:
#        prefer-ip-address: true
#    client:
#        fetch-registry: true
#        register-with-eureka: true